### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by C1PO** [Xinhao-Deng/Website-Fingerprinting-Library#3]
When I run the DF.SH script I got the following error.
Just to try, I commented the test.py part so I ran only the train phase and I'm usign the CPU so I delete the args because the script take the cpu as default device.
I'm using the Closed_2tab dataset.
```
/home/leo/.local/share/virtualenvs/Website-Fingerprinting-Library-y94zcj3G/lib/python3.8/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
loading train file:  ./datasets/Closed_2tab/train.npz
Train: X=torch.Size([46980, 1, 5000]), y=torch.Size([46980, 100])
Valid: X=torch.Size([5220, 1, 5000]), y=torch.Size([5220, 100])
num_classes: 2
No pre-trained model
Traceback (most recent call last):
  File "exp/train.py", line 115, in <module>
    model_utils.model_train(
  File "/home/leo/.local/share/virtualenvs/Website-Fingerprinting-Library-y94zcj3G/lib/python3.8/site-packages/WFlib/tools/model_utils.py", line 163, in model_train
    loss = criterion(outs, cur_y)
  File "/home/leo/.local/share/virtualenvs/Website-Fingerprinting-Library-y94zcj3G/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/leo/.local/share/virtualenvs/Website-Fingerprinting-Library-y94zcj3G/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/leo/.local/share/virtualenvs/Website-Fingerprinting-Library-y94zcj3G/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1188, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/home/leo/.local/share/virtualenvs/Website-Fingerprinting-Library-y94zcj3G/lib/python3.8/site-packages/torch/nn/functional.py", line 3104, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: 0D or 1D target tensor expected, multi-target not supported
```

How can I solve it?

**Comment by Xinhao-Deng** [comment]
For the multi-tab dataset, you need to adjust parameters such as `--num_tab 2` and `--loss BCEWithLogitsLoss`. More details on parameters can be found in `exp/train.py`.
